permalink: pretty
markdown: kramdown
url: https://mahadishere.github.io
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Mahad Mufti
collections:
  projects:
    output: false
    permalink: /projects/:name/
title: Mahad's Portfolio
timezone: UTC
exclude:
  - README.txt
  - LICENSE.txt
description: Hand curated projects in AR/VR, AI/MML, apps and games.
baseurl: /portfolio
